//
//  ChatMessage.swift
//  OpenAIKit
//
//  Copyright (c) 2023 OpenDive
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.
//

import Foundation

/// The chat message object used for each chat conversation message.
public struct ChatMessage: Codable, Identifiable, Sendable {
    private enum CodingKeys: String, CodingKey {
        case role, content
        case functionCall = "function_call"
    }

    /// ID used for iterating through list of chat messages
    public var id = UUID().uuidString

    /// The person sending the message
    public let role: ChatRole

    /// The message itself
    public let content: String?

    /// The name and arguments of a function that should be called, as generated by the model.
    public let functionCall: FunctionCall?

    public init(role: ChatRole, content: String? = nil, functionCall: FunctionCall? = nil) {
        self.role = role
        self.content = content
        self.functionCall = functionCall
    }

    public var body: [String: String] {
        if let content {
            return [
                "role": self.role.rawValue,
                "content": content
            ]
        }
        return ["role": self.role.rawValue, "content": ""]
    }
}
